// Core imports
import type { Metadata } from "next";

// User imports
import StoreProvider from "@/store/StoreProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
